[package]
name = "token_bridge_contract"
authors = ["Anmol Bansal <anmolbansal1807@gmail.com>"]
type = "contract"

[dependencies]
token = { git = "https://github.com/AztecProtocol/aztec-standards", tag = "v6.0.0-rc.1", directory = "src/token_contract" }
token_minter_proxy = { path = "../token_minter_proxy" }
claim_secret_lib = { path = "../claim_secret" }
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
token_portal_content_hash_lib = { git = "https://github.com/aztec-labs-eng/aztec-node", tag = "v6.0.0-rc.1", directory = "noir-projects/noir-contracts/contracts/libs/token_portal_content_hash_lib" }
