[package]
name = "token_minter_proxy"
authors = ["Anmol Bansal <anmolbansal1807@gmail.com>"]
type = "contract"

[dependencies]
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
token = { path = "../token" }
