/** Stable hooks for the e2e suite; copy and layout may change freely around them. */
export const TESTIDS = {
	l1Connect: "l1-connect",
	l1Status: "l1-status",
	l1SwitchChain: "l1-switch-chain",
	l1Disconnect: "l1-disconnect",
	aztecConnect: "aztec-connect",
	aztecStatus: "aztec-status",
	aztecError: "aztec-error",
	aztecRetry: "aztec-retry",
	walletPicker: "wallet-picker",
	walletPickerRow: "wallet-picker-row",
	walletPickerConnect: "wallet-picker-connect",
	walletPickerCancel: "wallet-picker-cancel",
	verificationModal: "verification-modal",
	verificationGrid: "verification-grid",
	btnVerifyConfirm: "verify-confirm",
	btnVerifyCancel: "verify-cancel",
	accountChoice: "account-choice",
	accountChoiceRow: "account-choice-row",
	accountChoiceContinue: "account-choice-continue",
	accountChoiceCancel: "account-choice-cancel",
	accountChip: "account-chip",
	accountMenu: "account-menu",
	accountMenuRow: "account-menu-row",
	aztecDisconnect: "aztec-disconnect",
	notice: "notice",
} as const
